name: Clean Data Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas

      - name: Run cleaning script
        run: python clean_data.py

      - name: Commit cleaned files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add clean_deliveries.csv clean_stops.csv
          git commit -m "Auto clean data" || echo "No changes"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
